name: Nightly Pipeline Release

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 5am UTC
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Run tests during release'
        required: false
        type: boolean
        default: false

jobs:
  release:
    uses: ./.github/workflows/nightly-release-template.yml
    with:
      project-name: 'pipeline'
      git-repository: 'tektoncd/pipeline'
      container-registry: 'ghcr.io'
      container-registry-path: 'tektoncd/pipeline'
      run-tests: ${{ inputs.run-tests || false }}
    secrets:
      RELEASE_SECRET: ${{ secrets.RELEASE_SECRET }}
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }} 